# Generated by Django 4.2.1 on 2023-06-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('productos', models.ManyToManyField(to='Tienda.producto')),
            ],
        ),
    ]
