# Generated by Django 4.2.1 on 2023-06-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
    ]
